name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build Quarkus application
        run: ./gradlew build -Dquarkus.package.type=native

      - name: Build Docker image
        run: docker build -f src/main/docker/Dockerfile.native-micro -t quarkus/anime-quote .