name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MONGO_CONNECTION: ${{ secrets.MONGO_CONNECTION }}
      MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}  
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configurar ambiente
        run: |
          echo "MONGO_CONNECTION=${MONGO_CONNECTION}" >> .env
          echo "MONGO_DATABASE=${MONGO_DATABASE}" >> .env
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Quarkus application
        run: ./gradlew build -Dquarkus.package.type=native

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: src/main/docker/Dockerfile.native-micro
          push: true
          tags: maxhardev/animequote:latest